var statuses = [
  { id: 1, label: "in-progress", color: "black" },
  { id: 2, label: "done", color: "black" },
  { id: 3, label: "experimental", color: "black" },
];

var outputs = [
  { id: 1, label: "study", color: "black" },
  { id: 2, label: "application", color: "black" },
  { id: 3, label: "map / visualization", color: "black" },
  { id: 4, label: "analysis", color: "black" },
];

const tagColor = "grey";
var tags = [
  { id: 1, label: "JS | reactJS" },
  { id: 2, label: "leafletJS" },
  { id: 3, label: "nodeJS" },
  { id: 4, label: "Python" },
  { id: 5, label: "R" },
  { id: 6, label: "PostGres | PostGIS" },
  { id: 7, label: "rethinkDB" },
  { id: 8, label: "mySQL | mariaDB" },
  { id: 9, label: "d3 | vegas" },
  { id: 10, label: "HTML5 Canvas" },
  { id: 11, label: "GIS analysis" },
  { id: 12, label: "network analysis" },
  { id: 13, label: "digital humanities" },
  { id: 14, label: "complex systems" },
  { id: 15, label: "analytical systems" },
  { id: 16, label: "REST" },
  { id: 17, label: "weather analysis" },
  { id: 18, label: "environmental data" },
  { id: 19, label: "spatiotemporal | real-time" },
  { id: 20, label: "transportation data" },
  { id: 21, label: "game" },
  { id: 22, label: "graphs db | neo4J" },
  { id: 23, label: "data mining" },
];

tags.forEach((tag) => (tag["color"] = tagColor));

var itemsProject = [
  {
    time: "2018",
    label: "Baptisteries",
    text: "",
    image: "",
    status: [2],
    output: [3],
    tags: [1, 9, 3, 11, 13],
    links: {
      map: "",
    },
  },
  {
    time: "2018 — 2019",
    label: "Historical Geocoding Assistant",
    text: "",
    image: "",
    status: [2],
    output: [2],
    tags: [1, 2, 13],
    links: {},
  },
  {
    time: "2019",
    label: "Map of Lollards",
    text: "",
    image: "",
    status: [2],
    output: [3],
    tags: [1, 2, 13],
    links: {},
  },
  {
    time: "2019",
    label: "Map of Cathar Houses",
    text: "",
    image: "",
    status: [2],
    output: [3],
    tags: [1, 2, 13],
    links: {},
  },
  {
    time: "2017",
    label: "GEHIR Map",
    text: "",
    image: "",
    status: [2],
    output: [1, 2, 3, 4],
    tags: [1, 2, 11, 13],
    links: {},
  },
  {
    time: "2017 — 2020",
    label: "Analysis of the spread of Egyptian cults in Eastern Mediteranean",
    text: "",
    image: "",
    status: [2],
    output: [1, 3, 4],
    tags: [3, 4, 11, 12, 13, 14],
    links: {},
  },
  {
    time: "2017 — 2018",
    label: "",
    text: "Simulations and ABM in Roman World",
    image: "",
    status: [2],
    output: [1, 4],
    tags: [4, 12, 13, 14],
    links: {},
  },
  {
    time: "2014 — 2017",
    label: "Archaeological database of Bohemian-Moravian Highlands",
    text: "",
    image: "",
    status: [2],
    output: [1, 3, 4],
    tags: [2, 3, 5, 6, 11, 12, 15, 19],
    links: {},
  },
  {
    time: "",
    label: "Analytical dashboard for radio broadcasting data",
    text: "",
    image: "",
    status: [2, 3],
    output: [2],
    tags: [1, 4, 6, 15, 16, 19],
    links: {},
  },
  {
    time: "2018",
    label: "Map framework for the project of Digitizing Patterns of Power",
    text: "",
    image: "",
    status: [2],
    output: [1, 2, 3],
    tags: [1, 2, 6, 16],
    links: {},
  },
  {
    time: "2018 — 2019",
    label: "Albina",
    text: "",
    image: "",
    status: [],
    output: [2],
    tags: [1, 2, 4, 17, 18],
    links: {},
  },
  {
    time: "2018 — 2019",
    label: "BesteLagen",
    text: "",
    image: "",
    status: [2],
    output: [2],
    tags: [1, 2, 3, 8],
    links: {},
  },
  {
    time: "2014 — 2015",
    label: "Application for study of low-emission zones",
    text: "",
    image: "",
    status: [2, 3],
    output: [1, 2, 3, 4],
    tags: [1, 10, 11, 12, 20],
    links: {},
  },
  {
    time: "",
    label: "Gods on the barge",
    text: "",
    image: "",
    status: [2, 3],
    output: [1, 2],
    tags: [1, 10, 14, 21],
    links: {},
  },
  {
    time: "",
    label: "ArchaeoDB",
    text: "",
    image: "",
    status: [2],
    output: [2],
    tags: [1, 3, 7, 15],
    links: {},
  },
  {
    time: "",
    label: "Dissinet Database",
    text: "",
    image: "",
    status: [1],
    output: [2],
    tags: [1, 22, 15, 13, 3],
    links: {},
  },
  {
    time: "",
    label: "Monasteries",
    text: "",
    image: "",
    status: [1],
    output: [1],
    tags: [3, 7, 23, 15],
    links: {},
  },
  {
    time: "",
    label: "",
    text: "",
    image: "",
    status: [],
    output: [],
    tags: [],
    links: {},
  },
];
