var itemsWork = [
  {
    time: "Jan 2019 – ",
    position: "Geospatial Developer | UI Developer",
    company: "Freelancing",
    location: "remote",
    description: [
      "Designed and developed various on-demand web-based applications, data dashboards, maps, and visualizations from conception to deployment.",
    ],
    skills: [
      "React.js",
      "TypeScript",
      "PostgreSQL",
      "NoSQL",
      "D3.js",
      "HTML5 Canvas",
      "Node.js",
      "Jest",
      "Python",
      "QGIS",
    ],
  },
  {
    time: "Mar 2023 – Apr 2024",
    position: "Data Visualization Engineer",
    company: "Seldon",
    link: "https://www.seldon.io",
    location: "London, UK",
    description: [
      "Created designs and code for various data-science-related interactive visual components",
      "Played a critical role in refactoring the existing product front-end codebase",
    ],
    skills: ["TypeScript", "React.js", "Figma", "Data visualization", "D3.js"],
  },
  {
    time: "Oct 2020 — Dec 2022",
    position: "Postdoc researcher | GIS Engineer | UI developer",
    company: "Casus Science | HZDR",
    link: "https://www.casus.science/",
    location: "Goerlitz | Dresden, DE",
    description: [
      "Led the development of the web infrastructure of www.where2test.de, including designing and implementing interactive visual components",
      "Managed data processing and data integration pipelines",
      "Conducted data-driven analyses on epidemiological and environmental data and utilized data visualization techniques",
      "Designed and utilized data visualization components and tools",
    ],
    skills: [
      "TypeScript",
      "React.js",
      "PostgreSQL",
      "PostGIS",
      "D3.js",
      "HTML5 Canvas",
      "Python Flask",
      "Scikit-Learn",
      "NetworkX",
      "QGIS",
      "Figma",
      "Vega",
      "GDAL",
      "Leaflet",
    ],
  },
  {
    time: "Jan 2019 – Nov 2020",
    position: "GIS Data Analyst",
    company: "Czech Academy of Science",
    link: "https://www.avcr.cz/en/",
    location: "Brno | Prague, CZ",
    description: [
      "Built processing pipelines for geospatial environmental data and prepared visualizations",
    ],
    skills: ["Geo/Pandas", "Python", "QGIS", "Data visualization"],
  },

  {
    time: "Aug 2015 – Nov 2020",
    position: "Researcher | GIS Engineer",
    company: "Masaryk University",
    location: "Brno, CZ",
    link: "https://www.muni.cz/en",
    description: [
      "Administrated projects involving geospatial data acquisition, scraping, modeling, storage, analysis, and interactive visualization",
      "Conducted interdisciplinary research in various scientific fields, including archaeology, history, and environmental studies",
      "Developed several data-centric applications including the interactive frontend, server, and database.",
      "Taught geospatial technologies and data analysis classes at the University",
    ],
    skills: [
      "QGIS",
      "React",
      "Javascript | Typescript",
      "PostgreSQL",
      "PostGIS",
      "NoSQL",
      "D3.js",
      "HTML5 Canvas",
      "QGIS",
      "GDAL",
      "Leaflet",
    ],
  },
  {
    time: "Apr 2017 – Mar 2019",
    position: "Geospatial Developer",
    company:
      "University of Vienna, Department of Geography and Regional Research",
    link: "https://www.univie.ac.at/en/",
    location: "Vienna, AT",
    description: [
      "Designed and built map-centered web applications using React and TS|JS",
      "Maintained and extended existing GIS pipelines",
      "Developed and implemented custom visualization methods and tools",
    ],
    skills: [
      "TypeScript",
      "React.js",
      "SCSS",
      "MariaDB",
      "D3.js",
      "HTML5 Canvas",
      "Leaflet",
    ],
  },
  {
    time: "Sep 2014 – Nov 2015",
    position: "React Developer",
    company: "CDV - Transport Research Centre",
    link: "https://www.cdv.cz/en/",
    location: "Brno , CZ",
    description: [
      "Helped developing company internal information system using React and Coffeescript",
    ],
    skills: ["Coffeescript", "React", "sequelize"],
  },
];

export default itemsWork;
