var itemsWork = [
  {
    time: "Oct 2020 — Dec 2022",
    label: "Postdoc researcher | UI developer",
    text1: "Casus Science | HZDR",
    link1: "https://www.casus.science/",
    location: "Goerlitz | Dresden, DE",
    description: [
      "Led the development of the web infrastructure of www.where2test.de, including designing and implementing interactive visual components",
      "Managed data processing and data integration pipelines",
      "Conducted data-driven analyses on epidemiological and environmental data and utilized data visualization techniques",
      "Designed and utilized data visualization components and tools",
    ],
    skills: [
      "TypeScript",
      "React.js",
      "PostgreSQL",
      "PostGIS",
      "D3.js",
      "HTML5 Canvas",
      "Python Flask",
      "Scikit-Learn",
      "NetworkX",
      "QGIS",
      "Figma",
      "Vega",
      "GDAL",
      "Leaflet",
    ],
  },
  {
    time: "Jan 2019 – Nov 2020",
    label: "GIS Data Analyst",
    text1: "Czech Academy of Science",
    link1: "https://www.avcr.cz/en/",
    location: "Brno | Prague, CZ",
    description: [
      "Built processing pipelines for geospatial environmental data and prepared visualizations",
    ],
    skills: ["Geo/Pandas", "Python", "QGIS", "Data visualization"],
  },
  {
    time: "Jan 2019 – ",
    label: "Geospatial Developer | UI Developer",
    text1: "Freelancer",
    location: "-",
    description: [
      "Designed and developed various on-demand web-based applications, data dashboards, maps, and visualizations from conception to deployment.",
    ],
    skills: [
      "React.js",
      "TypeScript",
      "PostgreSQL",
      "NoSQL",
      "D3.js",
      "HTML5 Canvas",
      "Node.js",
      "Jest",
      "Python",
      "QGIS",
    ],
  },
  {
    time: "Aug 2015 – Nov 2020",
    label: "Researcher | GIS Engineer",
    text1: "Masaryk University",
    location: "Brno, CZ",
    link1: "https://www.muni.cz/en",
    description: [
      "Administrated projects involving geospatial data acquisition, scraping, modeling, storage, analysis, and interactive visualization",
      "Conducted interdisciplinary research in various scientific fields, including archaeology, history, and environmental studies",
      "Developed several data-centric applications including the interactive frontend, server, and database.",
      "Taught geospatial technologies and data analysis classes at the University",
    ],
    skills: [
      "QGIS",
      "React",
      "Javascript | Typescript",
      "PostgreSQL",
      "PostGIS",
      "NoSQL",
      "D3.js",
      "HTML5 Canvas",
      "QGIS",
      "GDAL",
      "Leaflet",
    ],
  },
  {
    time: "Apr 2017 – Mar 2019",
    label: "Geospatial Developer",
    text1:
      "University of Vienna, Department of Geography and Regional Research",
    link1: "https://www.univie.ac.at/en/",
    location: "Vienna, AT",
    description: [
      "Designed and built map-centered web applications using React and TS|JS",
      "Maintained and extended existing GIS pipelines",
      "Developed and implemented custom visualization methods and tools",
    ],
    skills: [
      "TypeScript",
      "React.js",
      "SCSS",
      "MariaDB",
      "D3.js",
      "HTML5 Canvas",
      "Leaflet",
    ],
  },
  {
    time: "Sep 2014 – Nov 2015",
    label: "React Developer",
    text1: "CDV - Transport Research Centre",
    link1: "https://www.cdv.cz/en/",
    location: "Brno , CZ",
    description: [
      "Built company internal information system using React and Coffeescript",
    ],
    skills: ["Coffeescript", "React", "sequelize"],
  },
];

export default itemsWork;
